RSGShared = RSGShared or {}
RSGShared.Items = {

    -----------------------------------------------
    -- REX CUSTOM ITEMS
    -----------------------------------------------
    campfire       = { name = 'campfire',       label = 'Camp Fire',       weight = 500,  type = 'item', image = 'campfire.png',       unique = false, useable = true,  shouldClose = true, description = 'add your description'},
    raw_meat       = { name = 'raw_meat',       label = 'Raw Meat',        weight = 50,   type = 'item', image = 'raw_meat.png',       unique = false, useable = false, shouldClose = true, description = 'add your description'},
    raw_fish       = { name = 'raw_fish',       label = 'Raw Fish',        weight = 50,   type = 'item', image = 'raw_fish.png',       unique = false, useable = false, shouldClose = true, description = 'add your description'},
    cooked_meat    = { name = 'cooked_meat',    label = 'Cooked Meat',     weight = 50,   type = 'item', image = 'cooked_meat.png',    unique = false, useable = true,  shouldClose = true, description = 'add your description'},
    cooked_fish    = { name = 'cooked_fish',    label = 'Cooked Fish',     weight = 50,   type = 'item', image = 'cooked_fish.png',    unique = false, useable = true,  shouldClose = true, description = 'add your description'},
    flour_wheat    = { name = 'flour_wheat',    label = 'Wheat Flour',     weight = 100,  type = 'item', image = 'flour_wheat.png',    unique = false, useable = false, shouldClose = true, description = 'add your description'},
    milk           = { name = 'milk',           label = 'Milk',            weight = 100,  type = 'item', image = 'milk.png',           unique = false, useable = true,  shouldClose = true, description = 'add your description'},
    egg            = { name = 'egg',            label = 'Egg',             weight = 100,  type = 'item', image = 'egg.png',            unique = false, useable = false, shouldClose = true, description = 'add your description'},
    bread_sour     = { name = 'bread_sour',     label = 'Sourdough Bread', weight = 100,  type = 'item', image = 'bread_sour.png',     unique = false, useable = true,  shouldClose = true, description = 'add your description'},
    coal           = { name = 'coal',           label = 'Coal',            weight = 100,  type = 'item', image = 'coal.png',           unique = false, useable = false, shouldClose = true, description = 'add your description'},
    steel_bar      = { name = 'steel_bar',      label = 'Steel Bar',       weight = 1000, type = 'item', image = 'steel_bar.png',      unique = false, useable = false, shouldClose = true, description = 'add your description'},
    wood           = { name = 'wood',           label = 'Wood',            weight = 100,  type = 'item', image = 'wood.png',           unique = false, useable = false, shouldClose = true, description = 'add your description'},
    pickaxe        = { name = 'pickaxe',        label = 'Pickaxe',         weight = 100,  type = 'item', image = 'pickaxe.png',        unique = false, useable = false, shouldClose = true, description = 'add your description'},
    shovel         = { name = 'shovel',         label = 'Shovel',          weight = 100,  type = 'item', image = 'shovel.png',         unique = false, useable = true,  shouldClose = true, description = 'add your description'},
    fishtrap       = { name = 'fishtrap',       label = 'Fish Trap',       weight = 1000, type = 'item', image = 'fishtrap.png',       unique = false, useable = true,  shouldClose = true, description = 'add your description'},
    trapbait       = { name = 'trapbait',       label = 'Trap Bait',       weight = 100,  type = 'item', image = 'trapbait.png',       unique = false, useable = false, shouldClose = true, description = 'add your description'},
    crayfish       = { name = 'crayfish',       label = 'Crayfish',        weight = 100,  type = 'item', image = 'crayfish.png',       unique = false, useable = false, shouldClose = true, description = 'add your description'},
    lobster        = { name = 'lobster',        label = 'Lobster',         weight = 100,  type = 'item', image = 'lobster.png',        unique = false, useable = false, shouldClose = true, description = 'add your description'},
    crab           = { name = 'crab',           label = 'Crab',            weight = 100,  type = 'item', image = 'crab.png',           unique = false, useable = false, shouldClose = true, description = 'add your description'},
    bluecrab       = { name = 'bluecrab',       label = 'Blue Crab',       weight = 100,  type = 'item', image = 'bluecrab.png',       unique = false, useable = false, shouldClose = true, description = 'add your description'},
    goldpan        = {name = 'goldpan',         label = 'Gold Pan',        weight = 100,  type = 'item', image = 'goldpan.png',        unique = false, useable = true,  shouldClose = true, description = 'add your description'},
    smallnugget    = {name = 'smallnugget',     label = 'Small Nugget',    weight = 100,  type = 'item', image = 'smallnugget.png',    unique = false, useable = false, shouldClose = true, description = 'add your description'},
    mediumnugget   = {name = 'mediumnugget',    label = 'Medium Nugget',   weight = 100,  type = 'item', image = 'mediumnugget.png',   unique = false, useable = false, shouldClose = true, description = 'add your description'},
    largenugget    = {name = 'largenugget',     label = 'Large Nugget',    weight = 100,  type = 'item', image = 'largenugget.png',    unique = false, useable = false, shouldClose = true, description = 'add your description'},
    boat_ticket    = { name = 'boat_ticket',    label = 'Boat Ticket',     weight = 100,  type = 'item', image = 'boat_ticket.png',    unique = false, useable = false, shouldClose = true, description = 'add your description'},
    rock           = { name = 'rock',           label = 'Rock',            weight = 1000, type = 'item', image = 'rock.png',           unique = false, useable = false, shouldClose = true, description = 'add your description'},
    saltrock       = { name = 'saltrock',       label = 'Salt Rock',       weight = 1000, type = 'item', image = 'saltrock.png',       unique = false, useable = false, shouldClose = true, description = 'add your description'},
    salt           = { name = 'salt',           label = 'Salt',            weight = 100,  type = 'item', image = 'salt.png',           unique = false, useable = false, shouldClose = true, description = 'add your description'},
    clay           = { name = 'clay',           label = 'Clay',            weight = 100,  type = 'item', image = 'clay.png',           unique = false, useable = false, shouldClose = true, description = 'add your description'},
    coal           = { name = 'coal',           label = 'Coal',            weight = 100,  type = 'item', image = 'coal.png',           unique = false, useable = false, shouldClose = true, description = 'add your description'},
    copper         = { name = 'copper',         label = 'Copper',          weight = 100,  type = 'item', image = 'copper.png',         unique = false, useable = false, shouldClose = true, description = 'add your description'},
    iron           = { name = 'iron',           label = 'Iron',            weight = 100,  type = 'item', image = 'iron.png',           unique = false, useable = false, shouldClose = true, description = 'add your description'},
    nitrate        = { name = 'nitrate',        label = 'Nitrate',         weight = 100,  type = 'item', image = 'nitrate.png',        unique = false, useable = false, shouldClose = true, description = 'add your description'},
    sulfur         = { name = 'sulfur',         label = 'Sulfur',          weight = 100,  type = 'item', image = 'sulfur.png',         unique = false, useable = false, shouldClose = true, description = 'add your description'},
    zinc           = { name = 'zinc',           label = 'Zinc',            weight = 100,  type = 'item', image = 'zinc.png',           unique = false, useable = false, shouldClose = true, description = 'add your description'},
    lead           = { name = 'lead',           label = 'Lead',            weight = 100,  type = 'item', image = 'lead.png',           unique = false, useable = false, shouldClose = true, description = 'add your description'},
    gold           = { name = 'gold',           label = 'Gold',            weight = 100,  type = 'item', image = 'gold.png',           unique = false, useable = false, shouldClose = true, description = 'add your description'},
    silver         = { name = 'silver',         label = 'Lead',            weight = 100,  type = 'item', image = 'silver.png',         unique = false, useable = false, shouldClose = true, description = 'add your description'},
    diamond_uncut  = { name = 'diamond_uncut',  label = 'Uncut Diamond',   weight = 100,  type = 'item', image = 'diamond_uncut.png',  unique = false, useable = false, shouldClose = true, description = 'add your description'},
    ruby_uncut     = { name = 'ruby_uncut',     label = 'Uncut Ruby',      weight = 100,  type = 'item', image = 'ruby_uncut.png',     unique = false, useable = false, shouldClose = true, description = 'add your description'},
    emerald_uncut  = { name = 'emerald_uncut',  label = 'Uncut Emerald',   weight = 100,  type = 'item', image = 'emerald_uncut.png',  unique = false, useable = false, shouldClose = true, description = 'add your description'},
    opal_uncut     = { name = 'opal_uncut',     label = 'Uncut Opal',      weight = 100,  type = 'item', image = 'opal_uncut.png',     unique = false, useable = false, shouldClose = true, description = 'add your description'},
    sapphire_uncut = { name = 'sapphire_uncut', label = 'Uncut Sapphire',  weight = 100,  type = 'item', image = 'sapphire_uncut.png', unique = false, useable = false, shouldClose = true, description = 'add your description'},
    storage_box    = { name = 'storage_box',    label = 'Storage Box',     weight = 1000, type = 'item', image = 'storage_box.png',    unique = true,  useable = true,  shouldClose = true, description = 'add your description'},
    -----------------------------------------------
    -- rex trapper
    -----------------------------------------------
    pelt_beaver_1star        = { name = 'pelt_beaver_1star',         label = 'Poor Beaver Pelt',           weight = 100, type = 'item', image = 'resource_pelt_beaver_star_1.png',               unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    pelt_beaver_2star        = { name = 'pelt_beaver_2star',         label = 'Good Beaver Pelt',           weight = 100, type = 'item', image = 'resource_pelt_beaver_star_2.png',               unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    pelt_beaver_3star        = { name = 'pelt_beaver_3star',         label = 'Perfect Beaver Pelt',        weight = 100, type = 'item', image = 'resource_pelt_beaver_star_3.png',               unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    skin_bear_1star          = { name = 'skin_bear_1star',           label = 'Poor Bear Skin',             weight = 100, type = 'item', image = 'resource_skin_bear_star_1.png',                 unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    skin_bear_2star          = { name = 'skin_bear_2star',           label = 'Good Bear Skin',             weight = 100, type = 'item', image = 'resource_skin_bear_star_2.png',                 unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    skin_bear_3star          = { name = 'skin_bear_3star',           label = 'Perfect Bear Skin',          weight = 100, type = 'item', image = 'resource_skin_bear_star_3.png',                 unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    skin_bear_black_1star    = { name = 'skin_bear_black_1star',     label = 'Bear Skin',                  weight = 100, type = 'item', image = 'resource_skin_bear_black_star_1.png',           unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    skin_bear_black_2star    = { name = 'skin_bear_black_2star',     label = 'Bear Skin',                  weight = 100, type = 'item', image = 'resource_skin_bear_black_star_2.png',           unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    skin_bear_black_3star    = { name = 'skin_bear_black_3star',     label = 'Bear Skin',                  weight = 100, type = 'item', image = 'resource_skin_bear_black_star_3.png',           unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    skin_javelina_boar_1star = { name = 'skin_javelina_boar_1star', label = 'Poor Javelina Skin',         weight = 100, type = 'item', image = 'resource_skin_javelina_boar_star_1.png',         unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    skin_javelina_boar_2star = { name = 'skin_javelina_boar_2star', label = 'Good Javelina Skin',         weight = 100, type = 'item', image = 'resource_skin_javelina_boar_star_2.png',         unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    skin_javelina_boar_3star = { name = 'skin_javelina_boar_3star', label = 'Perfect Javelina Skin',      weight = 100, type = 'item', image = 'resource_skin_javelina_boar_star_3.png',         unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    skin_buck_1star          = { name = 'skin_buck_1star',           label = 'Poor Buck Skin',             weight = 100, type = 'item', image = 'resource_skin_buck_star_1.png',                 unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    skin_buck_2star          = { name = 'skin_buck_2star',           label = 'Good Buck Skin',             weight = 100, type = 'item', image = 'resource_skin_buck_star_2.png',                 unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    skin_buck_3star          = { name = 'skin_buck_3star',           label = 'Perfect Buck Skin',          weight = 100, type = 'item', image = 'resource_skin_buck_star_3.png',                 unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    skin_buffalo_1star       = { name = 'skin_buffalo_1star',        label = 'Poor Buffalo Skin',          weight = 100, type = 'item', image = 'resource_skin_buffalo_star_1.png',              unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    skin_buffalo_2star       = { name = 'skin_buffalo_2star',        label = 'Good Buffalo Skin',          weight = 100, type = 'item', image = 'resource_skin_buffalo_star_2.png',              unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    skin_buffalo_3star       = { name = 'skin_buffalo_3star',        label = 'Perfect Buffalo Skin',       weight = 100, type = 'item', image = 'resource_skin_buffalo_star_3.png',              unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    hide_bull_1star          = { name = 'hide_bull_1star',           label = 'Poor Bull Hide',             weight = 100, type = 'item', image = 'resource_hide_cow_bull_star_1.png',             unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    hide_bull_2star          = { name = 'hide_bull_2star',           label = 'Good Bull Hide',             weight = 100, type = 'item', image = 'resource_hide_cow_bull_star_2.png',             unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    hide_bull_3star          = { name = 'hide_bull_3star',           label = 'Perfect Bull Hide',          weight = 100, type = 'item', image = 'resource_hide_cow_bull_star_3.png',             unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    pelt_cougar_1star        = { name = 'pelt_cougar_1star',         label = 'Poor Cougar Pelt',           weight = 100, type = 'item', image = 'resource_skin_cougar_star_1.png',               unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    pelt_cougar_2star        = { name = 'pelt_cougar_2star',         label = 'Good Cougar Pelt',           weight = 100, type = 'item', image = 'resource_skin_cougar_star_2.png',               unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    pelt_cougar_3star        = { name = 'pelt_cougar_3star',         label = 'Perfect Cougar Pelt',        weight = 100, type = 'item', image = 'resource_skin_cougar_star_3.png',               unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    hide_cow_1star           = { name = 'hide_cow_1star',            label = 'Poor Cow Hide',              weight = 100, type = 'item', image = 'resource_hide_cow2_star_1.png',                 unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    hide_cow_2star           = { name = 'hide_cow_2star',            label = 'Good Cow Hide',              weight = 100, type = 'item', image = 'resource_hide_cow2_star_2.png',                 unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    hide_cow_3star           = { name = 'hide_cow_3star',            label = 'Perfect Cow Hide',           weight = 100, type = 'item', image = 'resource_hide_cow2_star_3.png',                 unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    pelt_coyote_1star        = { name = 'pelt_coyote_1star',         label = 'Poor Coyote Pelt',           weight = 100, type = 'item', image = 'resource_pelt_coyote_star_1.png',               unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    pelt_coyote_2star        = { name = 'pelt_coyote_2star',         label = 'Good Coyote Pelt',           weight = 100, type = 'item', image = 'resource_pelt_coyote_star_2.png',               unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    pelt_coyote_3star        = { name = 'pelt_coyote_3star',         label = 'Perfect Coyote Pelt',        weight = 100, type = 'item', image = 'resource_pelt_coyote_star_3.png',               unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    skin_deer_1star          = { name = 'skin_deer_1star',           label = 'Poor Deer Skin',             weight = 100, type = 'item', image = 'resource_skin_deer_star_1.png',                 unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    skin_deer_2star          = { name = 'skin_deer_2star',           label = 'Good Deer Skin',             weight = 100, type = 'item', image = 'resource_skin_deer_star_2.png',                 unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    skin_deer_3star          = { name = 'skin_deer_3star',           label = 'Perfect Deer Skin',          weight = 100, type = 'item', image = 'resource_skin_deer_star_3.png',                 unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    pelt_elk_1star           = { name = 'pelt_elk_1star',            label = 'Poor Elk Pelt',              weight = 100, type = 'item', image = 'resource_skin_elk_star_1.png',                  unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    pelt_elk_2star           = { name = 'pelt_elk_2star',            label = 'Good Elk Pelt',              weight = 100, type = 'item', image = 'resource_skin_elk_star_2.png',                  unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    pelt_elk_3star           = { name = 'pelt_elk_3star',            label = 'Perfect Elk Pelt',           weight = 100, type = 'item', image = 'resource_skin_elk_star_3.png',                  unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    pelt_fox_1star           = { name = 'pelt_fox_1star',            label = 'Poor Fox Pelt',              weight = 100, type = 'item', image = 'resource_pelt_fox_star_1.png',                  unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    pelt_fox_2star           = { name = 'pelt_fox_2star',            label = 'Good Fox Pelt',              weight = 100, type = 'item', image = 'resource_pelt_fox_star_2.png',                  unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    pelt_fox_3star           = { name = 'pelt_fox_3star',            label = 'Perfect Fox Pelt',           weight = 100, type = 'item', image = 'resource_pelt_fox_star_3.png',                  unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    hide_goat_1star          = { name = 'hide_goat_1star',           label = 'Poor Goat Hide',             weight = 100, type = 'item', image = 'resource_skin_goat_star_1.png',                 unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    hide_goat_2star          = { name = 'hide_goat_2star',           label = 'Good Goat Hide',             weight = 100, type = 'item', image = 'resource_skin_goat_star_1.png',                 unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    hide_goat_3star          = { name = 'hide_goat_3star',           label = 'Perfect Goat Hide',          weight = 100, type = 'item', image = 'resource_skin_goat_star_1.png',                 unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    pelt_peccary_1star       = { name = 'pelt_peccary_1star',        label = 'Poor Peccary Pelt',          weight = 100, type = 'item', image = 'resource_pelt_peccary_star_1.png',              unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    pelt_peccary_2star       = { name = 'pelt_peccary_2star',        label = 'Good Peccary Pelt',          weight = 100, type = 'item', image = 'resource_pelt_peccary_star_2.png',              unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    pelt_peccary_3star       = { name = 'pelt_peccary_3star',        label = 'Perfect Peccary Pelt',       weight = 100, type = 'item', image = 'resource_pelt_peccary_star_3.png',              unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    pelt_moose_1star         = { name = 'pelt_moose_1star',          label = 'Poor Moose Pelt',            weight = 100, type = 'item', image = 'resource_skin_moose_star_1.png',                unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    pelt_moose_2star         = { name = 'pelt_moose_2star',          label = 'Good Moose Pelt',            weight = 100, type = 'item', image = 'resource_skin_moose_star_2.png',                unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    pelt_moose_3star         = { name = 'pelt_moose_3star',          label = 'Perfect Moose Pelt',         weight = 100, type = 'item', image = 'resource_skin_moose_star_3.png',                unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    hide_ox_1star            = { name = 'hide_ox_1star',             label = 'Poor Ox Hide',               weight = 100, type = 'item', image = 'resource_hide_cow_ox_star_1.png',               unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    hide_ox_2star            = { name = 'hide_ox_2star',             label = 'Good Ox Hide',               weight = 100, type = 'item', image = 'resource_hide_cow_ox_star_2.png',               unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    hide_ox_3star            = { name = 'hide_ox_3star',             label = 'Perfect Ox Hide',            weight = 100, type = 'item', image = 'resource_hide_cow_ox_star_3.png',               unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    pelt_panther_1star       = { name = 'pelt_panther_1star',        label = 'Poor Panther Pelt',          weight = 100, type = 'item', image = 'resource_skin_panther_star_1.png',              unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    pelt_panther_2star       = { name = 'pelt_panther_2star',        label = 'Good Panther Pelt',          weight = 100, type = 'item', image = 'resource_skin_panther_star_2.png',              unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    pelt_panther_3star       = { name = 'pelt_panther_3star',        label = 'Perfect Panther Pelt',       weight = 100, type = 'item', image = 'resource_skin_panther_star_3.png',              unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    skin_pig_1star           = { name = 'skin_pig_1star',            label = 'Poor Pig Skin',              weight = 100, type = 'item', image = 'resource_skin_pig_star_1.png',                  unique = false, useable = true, shouldClose = true, description = 'Poor Quality' },
    skin_pig_2star           = { name = 'skin_pig_2star',            label = 'Good Pig Skin',              weight = 100, type = 'item', image = 'resource_skin_pig_star_2.png',                  unique = false, useable = true, shouldClose = true, description = 'Good Quality' },
    skin_pig_3star           = { name = 'skin_pig_3star',            label = 'Perfect Pig Skin',           weight = 100, type = 'item', image = 'resource_skin_pig_star_3.png',                  unique = false, useable = true, shouldClose = true, description = 'Perfect Quality' },
    -----------------------------------------------
    hide_pronghorn_1star     = { name = 'hide_pronghorn_1star',      label = 'Poor Pronghorn Hide',        weight = 100, type = 'item', image = 'resource_skin_pronghorn_star_1.png',            unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    hide_pronghorn_2star     = { name = 'hide_pronghorn_2star',      label = 'Good Pronghorn Hide',        weight = 100, type = 'item', image = 'resource_skin_pronghorn_star_2.png',            unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    hide_pronghorn_3star     = { name = 'hide_pronghorn_3star',      label = 'Perfect Pronghorn Hide',     weight = 100, type = 'item', image = 'resource_skin_pronghorn_star_3.png',            unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    hide_ram_1star           = { name = 'hide_ram_1star',            label = 'Poor Ram Hide',              weight = 100, type = 'item', image = 'resource_skin_ram_star_1.png',                  unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    hide_ram_2star           = { name = 'hide_ram_2star',            label = 'Good Ram Hide',              weight = 100, type = 'item', image = 'resource_skin_ram_star_2.png',                  unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    hide_ram_3star           = { name = 'hide_ram_3star',            label = 'Perfect Ram Hide',           weight = 100, type = 'item', image = 'resource_skin_ram_star_3.png',                  unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    hide_sheep_1star         = { name = 'hide_sheep_1star',          label = 'Poor Sheep Hide',            weight = 100, type = 'item', image = 'resource_wool_star_1.png',                      unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    hide_sheep_2star         = { name = 'hide_sheep_2star',          label = 'Good Sheep Hide',            weight = 100, type = 'item', image = 'resource_wool_star_2.png',                      unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    hide_sheep_3star         = { name = 'hide_sheep_3star',          label = 'Perfect Sheep Hide',         weight = 100, type = 'item', image = 'resource_wool_star_3.png',                      unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    pelt_wolf_1star          = { name = 'pelt_wolf_1star',           label = 'Poor Wolf Pelt',             weight = 100, type = 'item', image = 'resource_pelt_wolf_star_1.png',                 unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    pelt_wolf_2star          = { name = 'pelt_wolf_2star',           label = 'Good Wolf Pelt',             weight = 100, type = 'item', image = 'resource_pelt_wolf_star_2.png',                 unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    pelt_wolf_3star          = { name = 'pelt_wolf_3star',           label = 'Perfect Wolf Pelt',          weight = 100, type = 'item', image = 'resource_pelt_wolf_star_3.png',                 unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    skin_alligator_1star     = { name = 'skin_alligator_1star',      label = 'Poor Alligator Skin',        weight = 100, type = 'item', image = 'resource_skin_alligator_star_1.png',            unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    skin_alligator_2star     = { name = 'skin_alligator_2star',      label = 'Good Alligator Skin',        weight = 100, type = 'item', image = 'resource_skin_alligator_star_2.png',            unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    skin_alligator_3star     = { name = 'skin_alligator_3star',      label = 'Perfect Alligator Skin',     weight = 100, type = 'item', image = 'resource_skin_alligator_star_3.png',            unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    pelt_raccoon_1star       = { name = 'pelt_raccoon_1star',        label = 'Poor Raccoon Pelt',          weight = 100, type = 'item', image = 'resource_pelt_raccoon_star_1.png',              unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    pelt_raccoon_2star       = { name = 'pelt_raccoon_2star',        label = 'Good Raccoon Pelt',          weight = 100, type = 'item', image = 'resource_pelt_raccoon_star_2.png',              unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    pelt_raccoon_3star       = { name = 'pelt_raccoon_3star',        label = 'Perfect Raccoon Pelt',       weight = 100, type = 'item', image = 'resource_pelt_raccoon_star_3.png',              unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    skin_alligator_1star     = { name = 'skin_alligator_1star',      label = 'Poor Alligator Skin',        weight = 100, type = 'item', image = 'resource_skin_alligator_star_1.png',            unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    skin_alligator_2star     = { name = 'skin_alligator_2star',      label = 'Good Alligator Skin',        weight = 100, type = 'item', image = 'resource_skin_alligator_star_2.png',            unique = false, useable = true, shouldClose = true, description = 'Good quality' },
    skin_alligator_3star     = { name = 'skin_alligator_3star',      label = 'Perfect Alligator Skin',     weight = 100, type = 'item', image = 'resource_skin_alligator_star_3.png',            unique = false, useable = true, shouldClose = true, description = 'Perfect quality' },
    -----------------------------------------------
    legendary_pelt           = { name = 'legendary_pelt',            label = 'Legendary Pelt',             weight = 100, type = 'item', image = 'legendary_pelt.png',                            unique = false, useable = true, shouldClose = true, description = 'Legendary' },
    feather                  = { name = 'feather',                   label = 'Feather',                    weight = 100, type = 'item', image = 'feather.png',                                   unique = false, useable = true, shouldClose = true, description = 'bird feather' },
    pelt_rabbit              = { name = 'pelt_rabbit',               label = 'Rabbit Pelt',                weight = 100, type = 'item', image = 'resource_pelt_rabbit.png',                      unique = false, useable = true, shouldClose = true, description = 'Animal pelt' },
    pelt_raccoon             = { name = 'pelt_raccoon ',             label = 'Raccoon Pelt',               weight = 100, type = 'item', image = 'resource_pelt_raccoon_star_1.png',              unique = false, useable = true, shouldClose = true, description = 'Poor quality' },
    pelt_skunk               = { name = 'pelt_skunk',                label = 'Skunk Pelt',                 weight = 100, type = 'item', image = 'resource_pelt_skunk.png',                       unique = false, useable = true, shouldClose = true, description = 'Animal pelt' },
    skin_blacktail_snake     = { name = 'skin_blacktail_snake',      label = 'Blacktail Rattlesnake Skin', weight = 100, type = 'item', image = 'resource_skin_snake_blacktail_rattlesnake.png', unique = false, useable = true, shouldClose = true, description = 'Snake skin' },
    skin_western_snake       = { name = 'skin_western_snake',        label = 'Western Rattlesnake Skin',   weight = 100, type = 'item', image = 'resource_snake_skin_western_rattlesnake.png',   unique = false, useable = true, shouldClose = true, description = 'Snake skin' },
    skin_water_snake         = { name = 'skin_water_snake',          label = 'Water Snake Skin',           weight = 100, type = 'item', image = 'resource_snake_skin_water.png',                 unique = false, useable = true, shouldClose = true, description = 'Snake skin' },
    skin_iguana_desert       = { name = 'skin_iguana_desert',        label = 'Desert Iguana Skin',         weight = 100, type = 'item', image = 'resource_skin_desert_iguana.png',               unique = false, useable = true, shouldClose = true, description = 'Reptile skin' },
    skin_iguana_green        = { name = 'skin_iguana_green',         label = 'Green Iguana Skin',          weight = 100, type = 'item', image = 'resource_skin_iguana_green.png',                unique = false, useable = true, shouldClose = true, description = 'Reptile skin' },
    skin_armadillo           = { name = 'skin_armadillo',            label = 'Armadillo Skin',             weight = 100, type = 'item', image = 'resource_skin_armadillo.png',                   unique = false, useable = true, shouldClose = true, description = 'Animal skin' },
    -----------------------------------------------

    -----------------------------------------------
    -- CORE ITEMS
    -----------------------------------------------
    -- general items
    bread      = { name = 'bread',      label = 'Bread',         weight = 100, type = 'item', image = 'consumable_bread_roll.png',     unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'Bread Roll' },
    water      = { name = 'water',      label = 'Water',         weight = 100, type = 'item', image = 'consumable_water_filtered.png', unique = false, useable = true, shouldClose = true, description = 'Drinkable Water' },
    stew       = { name = 'stew',       label = 'Stew',          weight = 100, type = 'item', image = 'consumable_stew_prison.png',    unique = false, useable = true, decay = 60, delete = true, shouldClose = true, description = 'Warm Stew' },
    coffee     = { name = 'coffee',     label = 'Coffee',        weight = 100, type = 'item', image = 'consumable_coffee.png',         unique = false, useable = true, decay = 10, delete = true, shouldClose = true, description = 'Hot Coffee' },
    canteen100 = { name = 'canteen100', label = 'Full Canteen',  weight = 500, type = 'item', image = 'canteen100.png',                unique = true,  useable = true, shouldClose = true, description = 'Canteen 100% Full'},
    canteen75  = { name = 'canteen75',  label = 'Canteen',       weight = 400, type = 'item', image = 'canteen75.png',                 unique = true,  useable = true, shouldClose = true, description = 'Canteen 75% Full'},
    canteen50  = { name = 'canteen50',  label = 'Canteen',       weight = 300, type = 'item', image = 'canteen50.png',                 unique = true,  useable = true, shouldClose = true, description = 'Canteen 50% Full'},
    canteen25  = { name = 'canteen25',  label = 'Canteen',       weight = 200, type = 'item', image = 'canteen25.png',                 unique = true,  useable = true, shouldClose = true, description = 'Canteen 25% Full'},
    canteen0   = { name = 'canteen0',   label = 'Empty Canteen', weight = 100, type = 'item', image = 'canteen0.png',                  unique = true,  useable = true, shouldClose = true, description = 'Empty Canteen'},
    handcuffs  = { name = 'handcuffs',  label = 'Hand Cuffs',    weight = 100, type = 'item', image = 'handcuffs.png',                 unique = false, useable = true, shouldClose = true, description = 'Used for cuffs' },

    -- horse items
    horse_brush         = { name = 'horse_brush',       label = 'Horse Brush',          weight = 100, type = 'item', image = 'horse_brush.png',                 unique = false, useable = true, shouldClose = true, description = 'Brush used to clean your horse' },
    horse_lantern       = { name = 'horse_lantern',     label = 'Horse Lantern',        weight = 100, type = 'item', image = 'horse_lantern.png',               unique = false, useable = true, shouldClose = true, description = 'To see in the dark' },
    horse_stimulant     = { name = 'horse_stimulant',   label = 'Horse Stimulant',      weight = 100, type = 'item', image = 'horse_stimulant.png',             unique = false, useable = true, shouldClose = true, description = 'Given to horses' },
    horse_reviver       = { name = 'horse_reviver',     label = 'Horse Reviver',        weight = 100, type = 'item', image = 'horse_reviver.png',               unique = false, useable = true, shouldClose = true, description = 'Given to horses' },
    horse_carrot        = { name = 'horse_carrot',      label = 'Horse Carrot',         weight = 100, type = 'item', image = 'horse_carrot.png',                unique = false, useable = true, shouldClose = true, description = 'Horses like these' },
    horse_apple         = { name = 'horse_apple',       label = 'Horse Apple',          weight = 100, type = 'item', image = 'horse_apple.png',                 unique = false, useable = true, shouldClose = true, description = 'A crisp snack for your horse' },
    sugarcube           = { name = 'sugarcube',         label = 'Sugar Cube',           weight = 100, type = 'item', image = 'sugarcube.png',                   unique = false, useable = true, shouldClose = true, description = 'Horses like these' },
    haysnack            = { name = 'haysnack',          label = 'Hay Snack',            weight = 100, type = 'item', image = 'hay_cube.png',                    unique = false, useable = true, shouldClose = true, description = 'Hay snack for horses' },
    horsemeal           = { name = 'horsemeal',         label = 'Horse Meal',           weight = 100, type = 'item', image = 'consumable_horse_meal.png',       unique = false, useable = true, shouldClose = true, description = 'A meal of oats for your horse' },

    -- animal items
    legendary_pelt = { name = 'legendary_pelt', label = 'Legendary Pelt', weight = 100, type = 'item', image = 'legendary_pelt.png', unique = false, useable = true, shouldClose = true, description = 'Legendary' },
    perfect_pelt   = { name = 'perfect_pelt',   label = 'Perfect Pelt',   weight = 100, type = 'item', image = 'perfect_pelt.png',   unique = false, useable = true, shouldClose = true, description = 'Perfect (* * *)' },
    good_pelt      = { name = 'good_pelt',      label = 'Good Pelt',      weight = 100, type = 'item', image = 'good_pelt.png',      unique = false, useable = true, shouldClose = true, description = 'Good (* *)' },
    poor_pelt      = { name = 'poor_pelt',      label = 'Poor Pelt',      weight = 100, type = 'item', image = 'poor_pelt.png',      unique = false, useable = true, shouldClose = true, description = 'Poor (*)' },
    reptile_skin   = { name = 'reptile_skin',   label = 'Reptile Skin',   weight = 100, type = 'item', image = 'reptile_skin.png',   unique = false, useable = true, shouldClose = true, description = 'snake skin' },
    feather        = { name = 'feather',        label = 'Feather',        weight = 100, type = 'item', image = 'feather.png',        unique = false, useable = true, shouldClose = true, description = 'bird feather' },
    animal_heart   = { name = 'animal_heart',   label = 'Animal Heart',   weight = 100, type = 'item', image = 'animal_heart.png',   unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'animal heart' },
    small_pelt     = { name = 'small_pelt',     label = 'Small Pelt',     weight = 100, type = 'item', image = 'small_pelt.png',     unique = false, useable = true, shouldClose = true, description = 'small animal pelt' },

    -- medical
    bandage      = { name = 'bandage',      label = 'Bandage',       weight = 100, type = 'item', image = 'bandage.png',      unique = false, useable = true, shouldClose = true, description = 'used to improve your health' },
    firstaid     = { name = 'firstaid',     label = 'First Aid',     weight = 100, type = 'item', image = 'firstaid.png',     unique = false, useable = true, shouldClose = true, description = 'used by medics to improve your health' },
    fieldbandage = { name = 'fieldbandage', label = 'Field Bandage', weight = 100, type = 'item', image = 'fieldbandage.png', unique = false, useable = true, shouldClose = true, description = 'patching yourself up' },

    -- Bird Post
    birdpost = { name = 'birdpost', label = 'Bird Post', weight = 5, type = 'item', image = 'birdpost.png', unique = false, useable = true, shouldClose = true, description = 'Bird Post for sending letters' },

    -- MoneyItems
    dollar       = { name = 'dollar',       label = 'Dollars',              weight = 1, type = 'item', image = 'dollar.png',       unique = false, useable = false, description = 'Standard currency used for everyday transactions'},
    cent         = { name = 'cent',         label = 'Cents',                weight = 3, type = 'item', image = 'cent.png',         unique = false, useable = false, description = 'Small denomination of currency, commonly used for change'},
    blood_dollar = { name = 'blood_dollar', label = 'Bloodstained Dollars', weight = 1, type = 'item', image = 'blood_dollar.png', unique = false, useable = false, description = 'Currency tainted by violence and crime'},
    blood_cent   = { name = 'blood_cent',   label = 'Bloodstained Cents',   weight = 3, type = 'item', image = 'blood_cent.png',   unique = false, useable = false, description = 'Small change stained with the remnants of bloodshed'},

    -- Money Clip
    money_clip       = { name = 'money_clip',       label = 'Money Clip',       weight = 1, type = 'item', image = 'money_clip.png',       unique = true, useable = true, shouldClose = true, description = 'Money Clip' },
    blood_money_clip = { name = 'blood_money_clip', label = 'Blood Money Clip', weight = 1, type = 'item', image = 'blood_money_clip.png', unique = true, useable = true, shouldClose = true, description = 'Blood Money Clip' },

    -- fishing
    a_c_fishbluegil_01_ms        = { name = 'a_c_fishbluegil_01_ms',        label = 'Blue Gil (M)',         weight = 600,  type = 'item', image = 'a_c_fishbluegil_01_ms.png',        unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishbluegil_01_sm        = { name = 'a_c_fishbluegil_01_sm',        label = 'Blue Gil (S)',         weight = 300,  type = 'item', image = 'a_c_fishbluegil_01_sm.png',        unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishbullheadcat_01_ms    = { name = 'a_c_fishbullheadcat_01_ms',    label = 'Bullhead Cat (M)',     weight = 600,  type = 'item', image = 'a_c_fishbullheadcat_01_ms.png',    unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishbullheadcat_01_sm    = { name = 'a_c_fishbullheadcat_01_sm',    label = 'Bullhead Cat (S)',     weight = 300,  type = 'item', image = 'a_c_fishbullheadcat_01_sm.png',    unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishchainpickerel_01_ms  = { name = 'a_c_fishchainpickerel_01_ms',  label = 'Chain Pickerel (M)',   weight = 600,  type = 'item', image = 'a_c_fishchainpickerel_01_ms.png',  unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishchainpickerel_01_sm  = { name = 'a_c_fishchainpickerel_01_sm',  label = 'Chain Pickerel (S)',   weight = 300,  type = 'item', image = 'a_c_fishchainpickerel_01_sm.png',  unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishchannelcatfish_01_lg = { name = 'a_c_fishchannelcatfish_01_lg', label = 'Channel Catfish (L)',  weight = 900,  type = 'item', image = 'a_c_fishchannelcatfish_01_lg.png', unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishchannelcatfish_01_xl = { name = 'a_c_fishchannelcatfish_01_xl', label = 'Channel Catfish (EL)', weight = 1000, type = 'item', image = 'a_c_fishchannelcatfish_01_xl.png', unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishlakesturgeon_01_lg   = { name = 'a_c_fishlakesturgeon_01_lg',   label = 'Lake Sturgeon (L)',    weight = 900,  type = 'item', image = 'a_c_fishlakesturgeon_01_lg.png',   unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishlargemouthbass_01_lg = { name = 'a_c_fishlargemouthbass_01_lg', label = 'Large Mouth Bass (L)', weight = 900,  type = 'item', image = 'a_c_fishlargemouthbass_01_lg.png', unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishlargemouthbass_01_ms = { name = 'a_c_fishlargemouthbass_01_ms', label = 'Large Mouth Bass (M)', weight = 600,  type = 'item', image = 'a_c_fishlargemouthbass_01_ms.png', unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishlongnosegar_01_lg    = { name = 'a_c_fishlongnosegar_01_lg',    label = 'Long Nose Gar (L)',    weight = 900,  type = 'item', image = 'a_c_fishlongnosegar_01_lg.png',    unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishmuskie_01_lg         = { name = 'a_c_fishmuskie_01_lg',         label = 'Muskie (L)',           weight = 900,  type = 'item', image = 'a_c_fishmuskie_01_lg.png',         unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishnorthernpike_01_lg   = { name = 'a_c_fishnorthernpike_01_lg',   label = 'Northern Pike (L)',    weight = 900,  type = 'item', image = 'a_c_fishnorthernpike_01_lg.png',   unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishperch_01_ms          = { name = 'a_c_fishperch_01_ms',          label = 'Perch (M)',            weight = 600,  type = 'item', image = 'a_c_fishperch_01_ms.png',          unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishperch_01_sm          = { name = 'a_c_fishperch_01_sm',          label = 'Perch (S)',            weight = 300,  type = 'item', image = 'a_c_fishperch_01_sm.png',          unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishrainbowtrout_01_lg   = { name = 'a_c_fishrainbowtrout_01_lg',   label = 'Rainbow Trout (L)',    weight = 900,  type = 'item', image = 'a_c_fishrainbowtrout_01_lg.png',   unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishrainbowtrout_01_ms   = { name = 'a_c_fishrainbowtrout_01_ms',   label = 'Rainbow Trout (M)',    weight = 600,  type = 'item', image = 'a_c_fishrainbowtrout_01_ms.png',   unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishredfinpickerel_01_ms = { name = 'a_c_fishredfinpickerel_01_ms', label = 'Red Fin Pickerel (M)', weight = 600,  type = 'item', image = 'a_c_fishredfinpickerel_01_ms.png', unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishredfinpickerel_01_sm = { name = 'a_c_fishredfinpickerel_01_sm', label = 'Red Fin Pickerel (S)', weight = 300,  type = 'item', image = 'a_c_fishredfinpickerel_01_sm.png', unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishrockbass_01_ms       = { name = 'a_c_fishrockbass_01_ms',       label = 'Rock Bass (M)',        weight = 600,  type = 'item', image = 'a_c_fishrockbass_01_ms.png',       unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishrockbass_01_sm       = { name = 'a_c_fishrockbass_01_sm',       label = 'Rock Bass (S)',        weight = 300,  type = 'item', image = 'a_c_fishrockbass_01_sm.png',       unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishsalmonsockeye_01_lg  = { name = 'a_c_fishsalmonsockeye_01_lg',  label = 'Salmon Sockeye (L)',   weight = 900,  type = 'item', image = 'a_c_fishsalmonsockeye_01_lg.png',  unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishsalmonsockeye_01_ml  = { name = 'a_c_fishsalmonsockeye_01_ml',  label = 'Salmon Sockeye (ML)',  weight = 800,  type = 'item', image = 'a_c_fishsalmonsockeye_01_ml.png',  unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishsalmonsockeye_01_ms  = { name = 'a_c_fishsalmonsockeye_01_ms',  label = 'Salmon Sockeye (M)',   weight = 600,  type = 'item', image = 'a_c_fishsalmonsockeye_01_ms.png',  unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishsmallmouthbass_01_lg = { name = 'a_c_fishsmallmouthbass_01_lg', label = 'Small Mouth Bass (L)', weight = 900,  type = 'item', image = 'a_c_fishsmallmouthbass_01_lg.png', unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishsmallmouthbass_01_ms = { name = 'a_c_fishsmallmouthbass_01_ms', label = 'Small Mouth Bass (M)', weight = 600,  type = 'item', image = 'a_c_fishsmallmouthbass_01_ms.png', unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },

    -- fishing bait
    p_baitbread01x   = { name = 'p_baitbread01x',   label = 'Bread Bait',    weight = 10, type = 'item', image = 'p_baitbread01x.png',   unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_baitcorn01x    = { name = 'p_baitcorn01x',    label = 'Corn Bait',     weight = 10, type = 'item', image = 'p_baitcorn01x.png',    unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_baitcheese01x  = { name = 'p_baitcheese01x',  label = 'Cheese Bait',   weight = 10, type = 'item', image = 'p_baitcheese01x.png',  unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_baitworm01x    = { name = 'p_baitworm01x',    label = 'Worm Bait',     weight = 10, type = 'item', image = 'p_baitworm01x.png',    unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_baitcricket01x = { name = 'p_baitcricket01x', label = 'Cricket Bait',  weight = 10, type = 'item', image = 'p_baitcricket01x.png', unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_crawdad01x     = { name = 'p_crawdad01x',     label = 'Crawfish Bait', weight = 10, type = 'item', image = 'p_crawdad01x.png',     unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },

    -- fishing lures
    p_finishedragonfly01x          = { name = 'p_finishedragonfly01x',          label = 'Dragonfly Lure',           weight = 10, type = 'item', image = 'p_finishedragonfly01x.png',          unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_finisdfishlure01x            = { name = 'p_finisdfishlure01x',            label = 'Fish Lure',                weight = 10, type = 'item', image = 'p_finisdfishlure01x.png',            unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_finishdcrawd01x              = { name = 'p_finishdcrawd01x',              label = 'Crawfish Lure',            weight = 10, type = 'item', image = 'p_finishdcrawd01x.png',              unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_finishedragonflylegendary01x = { name = 'p_finishedragonflylegendary01x', label = 'Legendary Dragonfly Lure', weight = 10, type = 'item', image = 'p_finishedragonflylegendary01x.png', unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_finisdfishlurelegendary01x   = { name = 'p_finisdfishlurelegendary01x',   label = 'Legendary Fish Lure',      weight = 10, type = 'item', image = 'p_finisdfishlurelegendary01x.png',   unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_finishdcrawdlegendary01x     = { name = 'p_finishdcrawdlegendary01x',     label = 'Legendary Crawfish Lure',  weight = 10, type = 'item', image = 'p_finishdcrawdlegendary01x.png',     unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_lgoc_spinner_v4              = { name = 'p_lgoc_spinner_v4',              label = 'Spinner',                  weight = 10, type = 'item', image = 'p_lgoc_spinner_v4.png',              unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_lgoc_spinner_v6              = { name = 'p_lgoc_spinner_v6',              label = 'Improved Spinner',         weight = 10, type = 'item', image = 'p_lgoc_spinner_v6.png',              unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },

    -----------------------------------------------
    -- WEAPONS
    -----------------------------------------------
    -- customice weapon
    gunsmith = { name = 'gunsmith', label = 'Gun craft', weight = 12000, type = 'item', image = 'guncraft.png', unique = false, useable = true,  shouldClose = true, description = 'Placeholder'},

    -- maintenance
    weapon_repair_kit = { name = 'weapon_repair_kit', label = 'Weapon Repair Kit', weight = 350, type = 'item', image = 'weapon_repair_kit.png', unique = false, useable = true, shouldClose = true, description = 'Used for weapon maintenance' },

    -- revolver
    weapon_revolver_cattleman              = { name = 'weapon_revolver_cattleman',              label = 'Cattleman Revolver',                weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_cattleman.png',              unique = true, useable = true, shouldClose = true, description = 'Takes revolver ammo' },
    weapon_revolver_cattleman_mexican      = { name = 'weapon_revolver_cattleman_mexican',      label = 'Cattleman Mexican Revolver',        weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_cattleman_mexican.png',      unique = true, useable = true, shouldClose = true, description = 'Takes revolver ammo' },
    weapon_revolver_doubleaction           = { name = 'weapon_revolver_doubleaction',           label = 'Double Action Revolver',            weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_doubleaction.png',           unique = true, useable = true, shouldClose = true, description = 'Takes revolver ammo' },
    weapon_revolver_doubleaction_gambler   = { name = 'weapon_revolver_doubleaction_gambler',   label = 'Double Action Gambler Revolver',    weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_doubleaction_gambler.png',   unique = true, useable = true, shouldClose = true, description = 'Takes revolver ammo' },
    weapon_revolver_schofield              = { name = 'weapon_revolver_schofield',              label = 'Schofield Revolver',                weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_schofield.png',               unique = true, useable = true, shouldClose = true, description = 'Takes revolver ammo' },
    weapon_revolver_lemat                  = { name = 'weapon_revolver_lemat',                  label = 'Lemat Revolver',                    weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_lemat.png',                  unique = true, useable = true, shouldClose = true, description = 'Takes revolver ammo' },
    weapon_revolver_navy                   = { name = 'weapon_revolver_navy',                   label = 'Navy Revolver',                     weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_navy.png',                   unique = true, useable = true, shouldClose = true, description = 'Takes revolver ammo' },
    weapon_revolver_navy_crossover         = { name = 'weapon_revolver_navy_crossover',         label = 'Navy Crossover Revolver',           weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_navy_crossover.png',         unique = true, useable = true, shouldClose = true, description = 'Takes revolver ammo' },
    -- pistol
    weapon_pistol_volcanic                 = { name = 'weapon_pistol_volcanic',                 label = 'Volcanic Pistol',                   weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL',   image = 'weapon_pistol_volcanic.png',                 unique = true, useable = true, shouldClose = true, description = 'Takes pistol ammo' },
    weapon_pistol_m1899                    = { name = 'weapon_pistol_m1899',                    label = 'm1899 Pistol',                      weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL',   image = 'weapon_pistol_m1899.png',                    unique = true, useable = true, shouldClose = true, description = 'Takes pistol ammo' },
    weapon_pistol_mauser                   = { name = 'weapon_pistol_mauser',                   label = 'Mauser Pistol',                     weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL',   image = 'weapon_pistol_mauser.png',                   unique = true, useable = true, shouldClose = true, description = 'Takes pistol ammo' },
    weapon_pistol_semiauto                 = { name = 'weapon_pistol_semiauto',                 label = 'Semi-Auto Pistol',                  weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL',   image = 'weapon_pistol_semiauto.png',                 unique = true, useable = true, shouldClose = true, description = 'Takes pistol ammo' },
    -- repeater
    weapon_repeater_carbine                = { name = 'weapon_repeater_carbine',                label = 'Carbine Repeater',                  weight = 1000, type = 'weapon', ammotype = 'AMMO_REPEATER', image = 'weapon_repeater_carbine.png',                unique = true, useable = true, shouldClose = true, description = 'Takes repeater ammo' },
    weapon_repeater_winchester             = { name = 'weapon_repeater_winchester',             label = 'Winchester Repeater',               weight = 1000, type = 'weapon', ammotype = 'AMMO_REPEATER', image = 'weapon_repeater_winchester.png',             unique = true, useable = true, shouldClose = true, description = 'Takes repeater ammo' },
    weapon_repeater_henry                  = { name = 'weapon_repeater_henry',                  label = 'Henry Repeater',                    weight = 1000, type = 'weapon', ammotype = 'AMMO_REPEATER', image = 'weapon_repeater_henry.png',                  unique = true, useable = true, shouldClose = true, description = 'Takes repeater ammo' },
    weapon_repeater_evans                  = { name = 'weapon_repeater_evans',                  label = 'Evans Repeater',                    weight = 1000, type = 'weapon', ammotype = 'AMMO_REPEATER', image = 'weapon_repeater_evans.png',                  unique = true, useable = true, shouldClose = true, description = 'Takes repeater ammo' },
    -- rifle
    weapon_rifle_varmint                   = { name = 'weapon_rifle_varmint',                   label = 'Varmint Rifle',                     weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',          image = 'weapon_rifle_varmint.png',             unique = true, useable = true, shouldClose = true, description = 'Takes rifle ammo' },
    weapon_rifle_springfield               = { name = 'weapon_rifle_springfield',               label = 'Springfield Rifle',                 weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',          image = 'weapon_rifle_springfield.png',         unique = true, useable = true, shouldClose = true, description = 'Takes rifle ammo' },
    weapon_rifle_boltaction                = { name = 'weapon_rifle_boltaction',                label = 'Boltaction Rifle',                  weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',          image = 'weapon_rifle_boltaction.png',          unique = true, useable = true, shouldClose = true, description = 'Takes rifle ammo' },
    weapon_rifle_elephant                  = { name = 'weapon_rifle_elephant',                  label = 'Elephant Rifle',                    weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE_ELEPHANT', image = 'weapon_rifle_elephant.png',            unique = true, useable = true, shouldClose = true, description = 'Takes elephant rifle ammo' },
    -- sniperrifle
    weapon_sniperrifle_rollingblock        = { name = 'weapon_sniperrifle_rollingblock',        label = 'Rollingblock Sniper Rifle',         weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',    image = 'weapon_sniperrifle_rollingblock.png',        unique = true, useable = true, shouldClose = true, description = 'Takes rifle ammo' },
    weapon_sniperrifle_rollingblock_exotic = { name = 'weapon_sniperrifle_rollingblock_exotic', label = 'Rollingblock Exotic Sniper Rifle',  weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',    image = 'weapon_sniperrifle_rollingblock_exotic.png', unique = true, useable = true, shouldClose = true, description = 'Takes rifle ammo' },
    weapon_sniperrifle_carcano             = { name = 'weapon_sniperrifle_carcano',             label = 'Rollingblock Carcano Sniper Rifle', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',    image = 'weapon_sniperrifle_carcano.png',             unique = true, useable = true, shouldClose = true, description = 'Takes rifle ammo' },
    -- shotgun
    weapon_shotgun_doublebarrel            = { name = 'weapon_shotgun_doublebarrel',            label = 'Double Barrel Shotgun',             weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_doublebarrel.png',            unique = true, useable = true, shouldClose = true, description = 'Takes shotgun ammo' },
    weapon_shotgun_doublebarrel_exotic     = { name = 'weapon_shotgun_doublebarrel_exotic',     label = 'Double Barrel Exotic Shotgun',      weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_doublebarrel_exotic.png',     unique = true, useable = true, shouldClose = true, description = 'Takes shotgun ammo' },
    weapon_shotgun_sawedoff                = { name = 'weapon_shotgun_sawedoff',                label = 'Sawedoff Shotgun',                  weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_sawedoff.png',                unique = true, useable = true, shouldClose = true, description = 'Takes shotgun ammo' },
    weapon_shotgun_semiauto                = { name = 'weapon_shotgun_semiauto',                label = 'Semi-Auto Shotgun',                 weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_semiauto.png',                unique = true, useable = true, shouldClose = true, description = 'Takes shotgun ammo' },
    weapon_shotgun_pump                    = { name = 'weapon_shotgun_pump',                    label = 'Pump Action Shotgun',               weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_pump.png',                    unique = true, useable = true, shouldClose = true, description = 'Takes shotgun ammo' },
    weapon_shotgun_repeating               = { name = 'weapon_shotgun_repeating',               label = 'Repeating Shotgun',                 weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_repeating.png',               unique = true, useable = true, shouldClose = true, description = 'Takes shotgun ammo' },
    -- bow
    weapon_bow                             = { name = 'weapon_bow',                             label = 'Sandard Bow',                       weight = 1000, type = 'weapon', ammotype = 'AMMO_ARROW',    image = 'weapon_bow.png',                             unique = true, useable = true, shouldClose = true, description = 'Takes arrow ammo' },
    weapon_bow_improved                    = { name = 'weapon_bow_improved',                    label = 'Improved Bow',                      weight = 1000, type = 'weapon', ammotype = 'AMMO_ARROW',    image = 'weapon_bow_improved.png',                    unique = true, useable = true, shouldClose = true, description = 'Takes arrow ammo' },
    -- lasso
    weapon_lasso                           = { name = 'weapon_lasso',                           label = 'Sandard Lasso',                     weight = 1000, type = 'equipment', ammotype = nil,          image = 'weapon_lasso.png',                           unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_lasso_reinforced                = { name = 'weapon_lasso_reinforced',                label = 'Reinforced Lasso',                  weight = 1000, type = 'equipment', ammotype = nil,          image = 'weapon_lasso_reinforced.png',                unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    -- melee / knife
    weapon_melee_knife                     = { name = 'weapon_melee_knife',                     label = 'Sandard Knife',                      weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_knife.png',                     unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_knife_jawbone             = { name = 'weapon_melee_knife_jawbone',             label = 'Jawbon Knife',                       weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_knife_jawbone.png',             unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_knife_trader              = { name = 'weapon_melee_knife_trader',              label = 'Tader Knife',                        weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_knife_trader.png',              unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_knife_horror              = { name = 'weapon_melee_knife_horror',              label = 'Horror Knife',                       weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_knife_horror.png',              unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_knife_rustic              = { name = 'weapon_melee_knife_rustic',              label = 'Rustic Knife',                       weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_knife_rustic.png',              unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_machete                   = { name = 'weapon_melee_machete',                   label = 'Machete',                            weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_machete.png',                   unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_machete_horror            = { name = 'weapon_melee_machete_horror',            label = 'Machete Horror',                     weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_machete_horror.png',            unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_machete_collector         = { name = 'weapon_melee_machete_collector',         label = 'Machete Collector',                  weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_machete_collector.png',         unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_torch                     = { name = 'weapon_melee_torch',                     label = 'Torch',                              weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_torch.png',                     unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    -- held
    weapon_melee_lantern                   = { name = 'weapon_melee_lantern',                   label = 'Lantern',                            weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_lantern.png',                   unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_davy_lantern              = { name = 'weapon_melee_davy_lantern',              label = 'Davy Lantern',                       weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_davy_lantern.png',              unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_lantern_halloween         = { name = 'weapon_melee_lantern_halloween',         label = 'Halloween Lantern',                  weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_lantern_halloween.png',         unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_kit_binoculars                  = { name = 'weapon_kit_binoculars',                  label = 'Binoculars',                         weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_kit_binoculars.png',                  unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_kit_binoculars_improved         = { name = 'weapon_kit_binoculars_improved',         label = 'Improved Binoculars',                weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_kit_binoculars_improved.png',         unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_kit_camera                      = { name = 'weapon_kit_camera',                      label = 'Camera',                             weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_kit_camera.png',                      unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_kit_camera_advanced             = { name = 'weapon_kit_camera_advanced',             label = 'Advanced Camera',                    weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_kit_camera_advanced.png',             unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_kit_metal_detector              = { name = 'weapon_kit_metal_detector',              label = 'Metal Detector',                     weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_kit_metal_detector.png',              unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    -- trown
    weapon_melee_hatchet                   = { name = 'weapon_melee_hatchet',                   label = 'Hatchet',                            weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_melee_hatchet.png',                   unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_hatchet_hunter            = { name = 'weapon_melee_hatchet_hunter',            label = 'Hunter Hatchet',                     weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_melee_hatchet_hunter.png',            unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_molotov                  = { name = 'weapon_thrown_molotov',                  label = 'Molotov',                            weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_molotov.png',                  unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_tomahawk                 = { name = 'weapon_thrown_tomahawk',                 label = 'Tomahawk',                           weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_tomahawk.png',                 unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_tomahawk_ancient         = { name = 'weapon_thrown_tomahawk_ancient',         label = 'Tomahawk Ancient',                   weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_tomahawk_ancient.png',         unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_dynamite                 = { name = 'weapon_thrown_dynamite',                 label = 'Dynamite',                           weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_dynamite.png',                 unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_poisonbottle             = { name = 'weapon_thrown_poisonbottle',             label = 'Poison Bottle',                      weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_poisonbottle.png',             unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_throwing_knives          = { name = 'weapon_thrown_throwing_knives',          label = 'Throwing Kives',                     weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_throwing_knives.png',          unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_cleaver                   = { name = 'weapon_melee_cleaver',                   label = 'Cleaver',                            weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_melee_cleaver.png',                   unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_bolas                    = { name = 'weapon_thrown_bolas',                    label = 'Balas',                              weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_bolas.png',                    unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_bolas_hawkmoth           = { name = 'weapon_thrown_bolas_hawkmoth',           label = 'Hawkmoth Balas',                     weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_bolas_hawkmoth.png',           unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_bolas_ironspiked         = { name = 'weapon_thrown_bolas_ironspiked',         label = 'Iron Spiked Balas',                  weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_bolas_ironspiked.png',         unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_bolas_intertwined        = { name = 'weapon_thrown_bolas_intertwined',        label = 'Intertwined Balas',                  weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_bolas_intertwined.png',        unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    -- fishing
    weapon_fishingrod                      = { name = 'weapon_fishingrod',                      label = 'Fishing Rod',                        weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_fishingrod.png',                      unique = true, useable = true, shouldClose = true, description = 'Placeholder' },

    -----------------------------------------------
    -- AMMO
    -----------------------------------------------
    ammo_arrow          = { name = 'ammo_arrow',          label = 'Arrow (N)', weight = 200, type = 'item', image = 'ammo_arrow.png',          unique = false, useable = true, shouldClose = true, description = 'Arrow' },
    ammo_arrow_small    = { name = 'ammo_arrow_small',    label = 'Arrow (S)', weight = 200, type = 'item', image = 'ammo_arrow.png',          unique = false, useable = true, shouldClose = true, description = 'Arrow' },
    ammo_arrow_fire     = { name = 'ammo_arrow_fire',     label = 'Arrow (F)', weight = 200, type = 'item', image = 'ammo_arrow_fire.png',     unique = false, useable = true, shouldClose = true, description = 'Arrow' },
    ammo_arrow_poison   = { name = 'ammo_arrow_poison',   label = 'Arrow (P)', weight = 200, type = 'item', image = 'ammo_arrow_poison.png',   unique = false, useable = true, shouldClose = true, description = 'Arrow' },
    ammo_arrow_dynamite = { name = 'ammo_arrow_dynamite', label = 'Arrow (D)', weight = 200, type = 'item', image = 'ammo_arrow_dynamite.png', unique = false, useable = true, shouldClose = true, description = 'Arrow' },

    -----------------------------------------------
    -- AMMO BOXES
    -----------------------------------------------
    ammo_box_revolver                    = { name = 'ammo_box_revolver',                    label = 'Ammo Box Revolver (N)',             weight = 100, type = 'item', image = 'ammo_box_revolver.png',                    unique = false, useable = true, shouldClose = true, description = 'Revolver Ammo Box' },
    ammo_box_revolver_express            = { name = 'ammo_box_revolver_express',            label = 'Ammo Box Revolver (E)',             weight = 100, type = 'item', image = 'ammo_box_revolver_express.png',            unique = false, useable = true, shouldClose = true, description = 'Revolver Ammo Box Express' },
    ammo_box_revolver_explosive          = { name = 'ammo_box_revolver_explosive',          label = 'Ammo Box Revolver (EE)',            weight = 100, type = 'item', image = 'ammo_box_revolver_explosive.png',          unique = false, useable = true, shouldClose = true, description = 'Revolver Ammo Box Express Explosive' },
    ammo_box_revolver_velocity           = { name = 'ammo_box_revolver_velocity',           label = 'Ammo Box Revolver (HV)',            weight = 100, type = 'item', image = 'ammo_box_revolver_velocity.png',           unique = false, useable = true, shouldClose = true, description = 'Revolver Ammo Box High Velocity' },
    ammo_box_revolver_splitpoint         = { name = 'ammo_box_revolver_splitpoint',         label = 'Ammo Box Revolver (SP)',            weight = 100, type = 'item', image = 'ammo_box_revolver_splitpoint.png',         unique = false, useable = true, shouldClose = true, description = 'Revolver Ammo Box Split Point' },
    ammo_box_pistol                      = { name = 'ammo_box_pistol',                      label = 'Ammo Box Pistol (N)',               weight = 100, type = 'item', image = 'ammo_box_pistol.png',                      unique = false, useable = true, shouldClose = true, description = 'Pistol Ammo Box' },
    ammo_box_pistol_express              = { name = 'ammo_box_pistol_express',              label = 'Ammo Box Pistol (E)',               weight = 100, type = 'item', image = 'ammo_box_pistol_express.png',              unique = false, useable = true, shouldClose = true, description = 'Pistol Ammo Box Express' },
    ammo_box_pistol_explosive            = { name = 'ammo_box_pistol_explosive',            label = 'Ammo Box Pistol (EE)',              weight = 100, type = 'item', image = 'ammo_box_pistol_explosive.png',            unique = false, useable = true, shouldClose = true, description = 'Pistol Ammo Box Express Explosive' },
    ammo_box_pistol_velocity             = { name = 'ammo_box_pistol_velocity',             label = 'Ammo Box Pistol (HV)',              weight = 100, type = 'item', image = 'ammo_box_pistol_velocity.png',             unique = false, useable = true, shouldClose = true, description = 'Pistol Ammo Box High Velocity' },
    ammo_box_pistol_splitpoint           = { name = 'ammo_box_pistol_splitpoint',           label = 'Ammo Box Pistol (SP)',              weight = 100, type = 'item', image = 'ammo_box_pistol_splitpoint.png',           unique = false, useable = true, shouldClose = true, description = 'Pistol Ammo Box Split Point' },
    ammo_box_repeater                    = { name = 'ammo_box_repeater',                    label = 'Ammo Box Repeater (N)',             weight = 100, type = 'item', image = 'ammo_box_repeater.png',                    unique = false, useable = true, shouldClose = true, description = 'Repeater Ammo Box' },
    ammo_box_repeater_express            = { name = 'ammo_box_repeater_express',            label = 'Ammo Box Repeater (E)',             weight = 100, type = 'item', image = 'ammo_box_repeater_express.png',            unique = false, useable = true, shouldClose = true, description = 'Repeater Ammo Box Express' },
    ammo_box_repeater_explosive          = { name = 'ammo_box_repeater_explosive',          label = 'Ammo Box Repeater (EE)',            weight = 100, type = 'item', image = 'ammo_box_repeater_explosive.png',          unique = false, useable = true, shouldClose = true, description = 'Repeater Ammo Box Express Explosive' },
    ammo_box_repeater_velocity           = { name = 'ammo_box_repeater_velocity',           label = 'Ammo Box Repeater (HV)',            weight = 100, type = 'item', image = 'ammo_box_repeater_velocity.png',           unique = false, useable = true, shouldClose = true, description = 'Repeater Ammo Box High Velocity' },
    ammo_box_repeater_splitpoint         = { name = 'ammo_box_repeater_splitpoint',         label = 'Ammo Box Repeater (SP)',            weight = 100, type = 'item', image = 'ammo_box_repeater_splitpoint.png',         unique = false, useable = true, shouldClose = true, description = 'Repeater Ammo Box Split Point' },
    ammo_box_rifle                       = { name = 'ammo_box_rifle',                       label = 'Ammo Box Rifle (N)',                weight = 100, type = 'item', image = 'ammo_box_rifle.png',                       unique = false, useable = true, shouldClose = true, description = 'Rifle Ammo Box' },
    ammo_box_rifle_express               = { name = 'ammo_box_rifle_express',               label = 'Ammo Box Rifle (E)',                weight = 100, type = 'item', image = 'ammo_box_rifle_express.png',               unique = false, useable = true, shouldClose = true, description = 'Rifle Ammo Box Express' },
    ammo_box_rifle_explosive             = { name = 'ammo_box_rifle_explosive',             label = 'Ammo Box Rifle (EE)',               weight = 100, type = 'item', image = 'ammo_box_rifle_explosive.png',             unique = false, useable = true, shouldClose = true, description = 'Rifle Ammo Box Express Explosive' },
    ammo_box_rifle_velocity              = { name = 'ammo_box_rifle_velocity',              label = 'Ammo Box Rifle (HV)',               weight = 100, type = 'item', image = 'ammo_box_rifle_velocity.png',              unique = false, useable = true, shouldClose = true, description = 'Rifle Ammo Box High Velocity' },
    ammo_box_rifle_splitpoint            = { name = 'ammo_box_rifle_splitpoint',            label = 'Ammo Box Rifle (SP)',               weight = 100, type = 'item', image = 'ammo_box_rifle_splitpoint.png',            unique = false, useable = true, shouldClose = true, description = 'Rifle Ammo Box Split Point' },
    ammo_box_shotgun                     = { name = 'ammo_box_shotgun',                     label = 'Ammo Box Shotgun (N)',              weight = 100, type = 'item', image = 'ammo_box_shotgun.png',                     unique = false, useable = true, shouldClose = true, description = 'Shotgun Ammo Box' },
    ammo_box_shotgun_buckshot_incendiary = { name = 'ammo_box_shotgun_buckshot_incendiary', label = 'Ammo Box Shotgun (BI)',             weight = 100, type = 'item', image = 'ammo_box_shotgun_buckshot_incendiary.png', unique = false, useable = true, shouldClose = true, description = 'Shotgun Ammo Box' },
    ammo_box_shotgun_slug                = { name = 'ammo_box_shotgun_slug',                label = 'Ammo Box Shotgun (S)',              weight = 100, type = 'item', image = 'ammo_box_shotgun_slug.png',                unique = false, useable = true, shouldClose = true, description = 'Shotgun Ammo Box' },
    ammo_box_shotgun_slug_explosive      = { name = 'ammo_box_shotgun_slug_explosive',      label = 'Ammo Box Shotgun (SE)',             weight = 100, type = 'item', image = 'ammo_box_shotgun_slug_explosive.png',      unique = false, useable = true, shouldClose = true, description = 'Shotgun Ammo Box' },
    ammo_box_rifle_elephant              = { name = 'ammo_box_rifle_elephant',              label = 'Ammo Box Elephant Rifle (N)',       weight = 100, type = 'item', image = 'ammo_box_rifle_elephant.png',              unique = false, useable = true, shouldClose = true, description = 'Elephant Rifle Ammo Box' },
    ammo_box_varmint                     = { name = 'ammo_box_varmint',                     label = 'Ammo Box Varmint Rifle (N)',        weight = 100, type = 'item', image = 'ammo_box_rifle.png',                       unique = false, useable = true, shouldClose = true, description = 'Varmint Rifle Ammo Box' },
    ammo_box_varmint_tranquilizer        = { name = 'ammo_box_varmint_tranquilizer',        label = 'Ammo Box Varmint Tranquilizer (N)', weight = 100, type = 'item', image = 'ammo_box_rifle.png',                       unique = false, useable = true, shouldClose = true, description = 'Varmint Rifle Tranquilizer Ammo Box' },

}
